max_depth: 4
linters:
  BorderZero:
    enabled: true
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  FinalNewline:
    enabled: true
  HexNotation:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero:
    enabled: true
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: true
  PropertySortOrder:
    enabled: true
  QualifyingElement:
    enabled: true
  SelectorDepth:
    enabled: true
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
  VendorPrefix:
    enabled: true